#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
feh --bg-fill /home/enikyasta/Pictures/Wallpapers/tara_jfvalois_burrard_inlet.jpg
#polybar &
$HOME/.java_wm.sh 
light-locker &
setxkbmap latam

#bspc monitor LVDS1 -n monitor0 -d I II III IV V VI VII VIII IX X
#bspc monitor HDMI4 -n monitor0 -d I II III IV V
#bspc monitor HDMI4 -n monitor0 -d I II III IV V VI VII VIII IX X
bspc monitor HDMI1 -n monitor1 -d VI VII VIII IX X
bspc monitor HDMI4 -n monitor0 -d I II III IV V
#bspc monitor eDP1 -n monitor0 -d I II III IV V VI VII VIII IX X
#bspc monitor DP-2 -n monitor0 -d I II III IV V VI VII VIII IX X
#bspc monitor HDMI4 -n monitor0 -d I II III IV V
#bspc monitor HDMI1 -n monitor1 -d VI VII VIII IX X
#bspc monitor HDMI-1 -s eDP-1
#bspc monitor HDMI4 -s HDMI2
#bspc DP1 -s HDMI4
#bspc monitor eDP-1 -s HDMI-1

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#000000"
bspc config normal_border_color  "#363636"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rula -a Visual-studio-code desktop=^1 state=floating center=true
