#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
nitrogen --restore &
$HOME/.config/polybar/launch.sh --shapes &
$HOME/.java_wm.sh &
setxkbmap latam &

bspc monitor eDP-1 -n monitor0 -d I II III IV V
bspc monitor HDMI-1 -n monitor1 -d VI VII VIII IX X
#bspc monitor HDMI-1 -s eDP-1
bspc monitor eDP-1 -s HDMI-1

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#000000"
bspc config normal_border_color  "#363636"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
